# Default values for jaeger-otel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

opentelemetry-collector:
  agentCollector:
    enabled: false
  standaloneCollector:
    enabled: true