# Default values for jaeger-otel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

opentelemetry-collector:
  agentCollector:
    enabled: false
  standaloneCollector:
    enabled: true
  config:
    exporters:
      jaeger:
        endpoint: my-tracing-jaeger-collector:14250
        insecure: true
    service:
      pipelines:
        metrics: null
        traces:
          exporters:
            - jaeger

jaeger:
  provisionDataStore:
    cassandra: false
  storage:
    type: elasticsearch
    elasticsearch:
      host: my-tracing-coordinating-only
      port: 9200

# elasticsearch elastic.co
# elasticsearch:
#   singleNode: true
#   antiAffinity: "soft"
#   esJavaOpts: "-Xmx47m -Xms47m"
#   image: docker.elastic.co/elasticsearch/elasticsearch-oss
#   imageTag: 7.10.2
#   resources:
#     requests:
#       memory: "100Mi"
#       cpu: "10m"
#     limits:
#       memory: "250Mi"
#       cpu: "800m"
#   volumeClaimTemplate:
#     accessModes: [ "ReadWriteOnce" ]
#     resources:
#       requests:
#         storage: 1Gi

# elasticsearch bitnami
elasticsearch:
  global:
    kibanaEnabled: true
  # master:
  #   replicas: 2
  # coordinating:
  #   replicas: 1
  # data:
  #   replicas: 2