apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: node0
  name: node0
spec:
  ports:
  - name: "8161"
    port: 8161
    targetPort: 8161
  selector:
    io.kompose.service: node0
status:
  loadBalancer: {}
