apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: node2
  name: node2
spec:
  ports:
  - name: "8163"
    port: 8163
    targetPort: 8161
  selector:
    io.kompose.service: node2
status:
  loadBalancer: {}
