apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: node1
  name: node1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: node1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -c
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: node1
    spec:
      containers:
      - env:
        - name: ARTEMIS_MAX_MEMORY
          value: 2000M
        - name: ARTEMIS_MIN_MEMORY
          value: 1512M
        - name: ARTEMIS_PASSWORD
          value: test
        - name: ARTEMIS_USERNAME
          value: test
        - name: ENABLE_JMX_EXPORTER
          value: "true"
        image: vromero/activemq-artemis:2.6.1
        imagePullPolicy: ""
        name: node1
        ports:
        - containerPort: 8161
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/artemis/etc-override
          name: node1-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: node1-claim0
        persistentVolumeClaim:
          claimName: node1-claim0
status: {}
