apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -c
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: node1
  name: node1
spec:
  ports:
  - name: "8162"
    port: 8162
    targetPort: 8161
  selector:
    io.kompose.service: node1
status:
  loadBalancer: {}
