
image:
  name: docker.io/afandy/demo-nest-simple
  tag: v1
build:
  enabled: false
deploy:
  env:
    - name: PORT
      value: "8080"
  readinessProbe:
    httpGet:
      path: /api
      port: http