apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-system
spec:
  secretName: ingress-cert
  commonName: faas.o6s.io
  dnsNames:
  - faas.o6s.io
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
